-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin_user_roles
(
    admin_user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    assigned_by uuid,
    assigned_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT admin_user_roles_pkey PRIMARY KEY (admin_user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.admin_users
(
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(200) COLLATE pg_catalog."default" NOT NULL,
    role admin_role NOT NULL,
    status admin_user_status NOT NULL,
    totp_secret character varying(32) COLLATE pg_catalog."default",
    totp_enabled boolean NOT NULL,
    last_login_at timestamp with time zone,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    password_reset_token character varying(64) COLLATE pg_catalog."default",
    password_reset_expires timestamp with time zone,
    CONSTRAINT admin_users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.alembic_version
(
    version_num character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE IF NOT EXISTS public.alerts
(
    alert_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    metric character varying(100) COLLATE pg_catalog."default" NOT NULL,
    dashboard character varying(50) COLLATE pg_catalog."default" NOT NULL,
    severity character varying(20) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    current_value double precision NOT NULL,
    threshold double precision NOT NULL,
    detail text COLLATE pg_catalog."default",
    feature character varying(100) COLLATE pg_catalog."default",
    model_type character varying(50) COLLATE pg_catalog."default",
    recommended_action text COLLATE pg_catalog."default",
    resolved_at timestamp with time zone,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT alerts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.api_keys
(
    organization_id uuid NOT NULL,
    key_hash character varying(64) COLLATE pg_catalog."default" NOT NULL,
    key_prefix character varying(12) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    environment api_key_environment NOT NULL,
    status api_key_status NOT NULL,
    last_used_at timestamp with time zone,
    created_by_user_id uuid,
    revoked_at timestamp with time zone,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    role_id uuid,
    CONSTRAINT api_keys_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.api_logs
(
    organization_id uuid,
    method character varying(10) COLLATE pg_catalog."default" NOT NULL,
    path character varying(500) COLLATE pg_catalog."default" NOT NULL,
    status_code integer NOT NULL,
    response_time_ms integer NOT NULL,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent character varying(500) COLLATE pg_catalog."default",
    request_id character varying(50) COLLATE pg_catalog."default",
    api_key_id uuid,
    api_key_prefix character varying(12) COLLATE pg_catalog."default",
    user_id uuid,
    error_detail text COLLATE pg_catalog."default",
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT api_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    actor_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    actor_id character varying(50) COLLATE pg_catalog."default",
    actor_email character varying(255) COLLATE pg_catalog."default",
    organization_id uuid,
    action character varying(100) COLLATE pg_catalog."default" NOT NULL,
    resource_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    resource_id character varying(50) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent character varying(500) COLLATE pg_catalog."default",
    request_id character varying(50) COLLATE pg_catalog."default",
    changes jsonb,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.batch_job_items
(
    id uuid NOT NULL,
    batch_job_id uuid NOT NULL,
    index integer NOT NULL,
    status batch_job_item_status NOT NULL DEFAULT 'pending'::batch_job_item_status,
    payload jsonb NOT NULL,
    score_request_id uuid,
    score_tracking_id character varying(50) COLLATE pg_catalog."default",
    error_code character varying(50) COLLATE pg_catalog."default",
    error_message text COLLATE pg_catalog."default",
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT batch_job_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bronze_ingestion_log
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    training_upload_id uuid NOT NULL,
    run_id uuid NOT NULL,
    source_blob_path text COLLATE pg_catalog."default" NOT NULL,
    source_checksum_sha256 text COLLATE pg_catalog."default" NOT NULL,
    source_file_size_bytes bigint NOT NULL,
    bronze_blob_path text COLLATE pg_catalog."default" NOT NULL,
    bronze_checksum_sha256 text COLLATE pg_catalog."default" NOT NULL,
    bronze_file_size_bytes bigint NOT NULL,
    ingestion_status text COLLATE pg_catalog."default" NOT NULL,
    error_message text COLLATE pg_catalog."default",
    ingested_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bronze_ingestion_log_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.bronze_ingestion_log
    IS 'Audit log for training data file ingestion to bronze layer. Tracks source and destination file details, checksums, and ingestion status.';

COMMENT ON COLUMN public.bronze_ingestion_log.run_id
    IS 'UUID identifying the specific ingestion run. Used for tracking and correlating related operations.';

COMMENT ON COLUMN public.bronze_ingestion_log.ingestion_status
    IS 'Status of ingestion: success, file_not_found, copy_failed, or verification_failed';

CREATE TABLE IF NOT EXISTS public.bulk_scoring_jobs
(
    organization_id uuid NOT NULL,
    file_name character varying(200) COLLATE pg_catalog."default",
    file_path character varying(500) COLLATE pg_catalog."default",
    status bulk_job_status NOT NULL,
    total_records integer,
    valid_records integer,
    invalid_records integer,
    processed_records integer NOT NULL,
    error_count integer NOT NULL,
    results_file_path character varying(500) COLLATE pg_catalog."default",
    error_report_path character varying(500) COLLATE pg_catalog."default",
    created_by_user_id uuid,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    job_id character varying(100) COLLATE pg_catalog."default",
    models_to_run jsonb,
    results_blob_path character varying(500) COLLATE pg_catalog."default",
    ingestion_status ingestion_status NOT NULL DEFAULT 'pending'::ingestion_status,
    ingested_count integer NOT NULL DEFAULT 0,
    CONSTRAINT bulk_scoring_jobs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.data_sources
(
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    short_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    source_type data_source_type NOT NULL,
    description text COLLATE pg_catalog."default",
    total_uploads integer NOT NULL DEFAULT 0,
    last_upload_at timestamp with time zone,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT data_sources_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.decision_metrics
(
    scoring_result_id uuid,
    decision character varying(30) COLLATE pg_catalog."default" NOT NULL,
    credit_score integer,
    score_grade character varying(5) COLLATE pg_catalog."default",
    risk_tier character varying(20) COLLATE pg_catalog."default",
    fraud_flag character varying(20) COLLATE pg_catalog."default",
    loan_tier character varying(20) COLLATE pg_catalog."default",
    probability_of_default double precision,
    data_quality_score double precision,
    applicant_age integer,
    has_explainability boolean,
    "timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT decision_metrics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.field_mappings
(
    training_upload_id uuid NOT NULL,
    source_field character varying(200) COLLATE pg_catalog."default" NOT NULL,
    target_feature character varying(100) COLLATE pg_catalog."default" NOT NULL,
    confidence numeric(5, 4) NOT NULL,
    confidence_level confidence_level NOT NULL,
    mapping_source mapping_source NOT NULL,
    sample_values jsonb,
    data_type_detected character varying(50) COLLATE pg_catalog."default",
    is_approved boolean NOT NULL DEFAULT false,
    admin_override_target character varying(100) COLLATE pg_catalog."default",
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT field_mappings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.loan_performances
(
    score_request_id uuid NOT NULL,
    status loan_performance_status NOT NULL,
    days_past_due integer,
    outstanding_balance numeric(15, 2),
    as_of_date date NOT NULL,
    reported_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT loan_performances_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mapping_templates
(
    data_source_id uuid NOT NULL,
    version integer NOT NULL,
    mappings jsonb NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_from_upload_id uuid,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT mapping_templates_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.message_deduplication
(
    run_id uuid NOT NULL,
    training_upload_id uuid NOT NULL,
    system_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    message_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    subscription_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    processed_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT message_deduplication_pkey PRIMARY KEY (run_id, system_name, message_id)
);

CREATE TABLE IF NOT EXISTS public.model_metrics
(
    model_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    model_version character varying(50) COLLATE pg_catalog."default",
    training_id character varying(100) COLLATE pg_catalog."default",
    metric_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    metrics jsonb,
    feature_drift jsonb,
    "timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT model_metrics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.model_versions
(
    version character varying(50) COLLATE pg_catalog."default" NOT NULL,
    model_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status model_status NOT NULL,
    metrics jsonb,
    feature_count integer,
    training_data_ref character varying(200) COLLATE pg_catalog."default",
    artifact_path character varying(500) COLLATE pg_catalog."default",
    description character varying(500) COLLATE pg_catalog."default",
    promoted_at timestamp with time zone,
    promoted_by_id uuid,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    training_upload_id uuid,
    data_source character varying(200) COLLATE pg_catalog."default",
    mlflow_run_id character varying(200) COLLATE pg_catalog."default",
    training_duration_seconds double precision,
    trained_at timestamp with time zone,
    training_status character varying(50) COLLATE pg_catalog."default",
    model_location jsonb,
    azure_ml_model jsonb,
    dataset_info jsonb,
    model_params jsonb,
    all_models_trained jsonb,
    all_models_metrics jsonb,
    training_id character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT model_versions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_model_versions_type_version UNIQUE (model_type, version)
);

COMMENT ON COLUMN public.model_versions.training_id
    IS 'AI pipeline training run ID, e.g. TRAIN-20260325-163000';

CREATE TABLE IF NOT EXISTS public.org_user_roles
(
    org_user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    assigned_by uuid,
    assigned_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT org_user_roles_pkey PRIMARY KEY (org_user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.org_users
(
    organization_id uuid NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(200) COLLATE pg_catalog."default" NOT NULL,
    role_label org_role_label NOT NULL,
    status org_user_status NOT NULL,
    totp_secret character varying(32) COLLATE pg_catalog."default",
    totp_enabled boolean NOT NULL,
    last_login_at timestamp with time zone,
    email_verification_token character varying(64) COLLATE pg_catalog."default",
    password_reset_token character varying(64) COLLATE pg_catalog."default",
    password_reset_expires timestamp with time zone,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT org_users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.organizations
(
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    short_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    industry_type industry_type NOT NULL,
    primary_contact_name character varying(200) COLLATE pg_catalog."default",
    primary_contact_email character varying(255) COLLATE pg_catalog."default",
    primary_contact_phone character varying(20) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    status org_status NOT NULL,
    suspension_reason text COLLATE pg_catalog."default",
    webhook_secret character varying(64) COLLATE pg_catalog."default",
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT organizations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.permissions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    group_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(300) COLLATE pg_catalog."default" NOT NULL,
    scope character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT permissions_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.pipeline_runs
(
    run_id uuid NOT NULL,
    training_upload_id uuid NOT NULL,
    bank_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    current_system character varying(100) COLLATE pg_catalog."default",
    started_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp without time zone,
    error_message text COLLATE pg_catalog."default",
    error_system character varying(100) COLLATE pg_catalog."default",
    silver_path character varying(500) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pipeline_runs_pkey PRIMARY KEY (run_id)
);

CREATE TABLE IF NOT EXISTS public.request_metrics
(
    endpoint character varying(500) COLLATE pg_catalog."default" NOT NULL,
    method character varying(10) COLLATE pg_catalog."default" NOT NULL,
    status_code integer NOT NULL,
    response_time_ms integer NOT NULL,
    "timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    request_id character varying(50) COLLATE pg_catalog."default",
    id uuid NOT NULL,
    CONSTRAINT request_metrics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description character varying(300) COLLATE pg_catalog."default",
    scope character varying(20) COLLATE pg_catalog."default" NOT NULL,
    organization_id uuid,
    is_system boolean NOT NULL DEFAULT false,
    created_by_user_id uuid,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT uq_role_name_org UNIQUE (name, organization_id)
);

CREATE TABLE IF NOT EXISTS public.score_decisions
(
    score_request_id uuid NOT NULL,
    decision decision_type NOT NULL,
    approved_amount numeric(15, 2),
    approved_tenure integer,
    interest_rate numeric(5, 4),
    decline_reason text COLLATE pg_catalog."default",
    decision_notes text COLLATE pg_catalog."default",
    decided_by_user_id uuid,
    decided_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT score_decisions_pkey PRIMARY KEY (id),
    CONSTRAINT score_decisions_score_request_id_key UNIQUE (score_request_id)
);

CREATE TABLE IF NOT EXISTS public.score_requests
(
    tracking_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    organization_id uuid NOT NULL,
    reference_id character varying(100) COLLATE pg_catalog."default",
    status score_request_status NOT NULL,
    request_source request_source NOT NULL,
    request_payload jsonb NOT NULL,
    applicant_hash character varying(64) COLLATE pg_catalog."default",
    score_value integer,
    risk_category character varying(20) COLLATE pg_catalog."default",
    confidence double precision,
    model_version character varying(50) COLLATE pg_catalog."default",
    processing_time_ms integer,
    api_key_id uuid,
    created_by_user_id uuid,
    idempotency_key character varying(100) COLLATE pg_catalog."default",
    scored_at timestamp with time zone,
    valid_until timestamp with time zone,
    callback_url character varying(500) COLLATE pg_catalog."default",
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT score_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.scoring_results
(
    request_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    score_request_id uuid,
    scoring_timestamp timestamp with time zone,
    decision scoring_decision NOT NULL,
    condition_applied jsonb,
    credit_risk jsonb,
    fraud_detection jsonb,
    loan_amount jsonb,
    income_verification jsonb,
    scoring_metadata jsonb,
    errors jsonb,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    bulk_job_id uuid,
    CONSTRAINT scoring_results_pkey PRIMARY KEY (id),
    CONSTRAINT scoring_results_request_id_key UNIQUE (request_id)
);

CREATE TABLE IF NOT EXISTS public.system_completions
(
    run_id uuid NOT NULL,
    training_upload_id uuid NOT NULL,
    system_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    started_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp without time zone,
    error_message text COLLATE pg_catalog."default",
    message_id character varying(255) COLLATE pg_catalog."default",
    subscription_name character varying(255) COLLATE pg_catalog."default",
    metadata jsonb,
    CONSTRAINT system_completions_pkey PRIMARY KEY (run_id, system_name)
);

CREATE TABLE IF NOT EXISTS public.training_data_sources
(
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    source_type source_type NOT NULL,
    provider character varying(200) COLLATE pg_catalog."default",
    data_period_start date,
    data_period_end date,
    record_count integer,
    quality_score numeric(3, 2),
    transformation_status training_data_status NOT NULL,
    raw_file_path character varying(500) COLLATE pg_catalog."default",
    transformed_path character varying(500) COLLATE pg_catalog."default",
    quality_report jsonb,
    uploaded_by_id uuid,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT training_data_sources_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.training_uploads
(
    data_source_id uuid NOT NULL,
    status upload_status NOT NULL,
    file_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    file_format file_format NOT NULL,
    file_size_bytes bigint,
    raw_file_path character varying(500) COLLATE pg_catalog."default",
    transformed_file_path character varying(500) COLLATE pg_catalog."default",
    file_metadata jsonb,
    record_count integer,
    valid_record_count integer,
    features_mapped integer,
    target_features_total integer NOT NULL DEFAULT 18,
    quality_report jsonb,
    quality_score numeric(3, 2),
    mapping_template_id uuid,
    rejection_reason text COLLATE pg_catalog."default",
    error_message text COLLATE pg_catalog."default",
    uploaded_by_id uuid,
    approved_by_id uuid,
    approved_at timestamp with time zone,
    completed_at timestamp with time zone,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    training_id character varying(100) COLLATE pg_catalog."default",
    models_to_train jsonb,
    CONSTRAINT training_uploads_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.training_uploads.training_id
    IS 'AI pipeline training run ID, e.g. TRAIN-20260325-163000';

COMMENT ON COLUMN public.training_uploads.models_to_train
    IS 'List of models requested for training';

CREATE TABLE IF NOT EXISTS public.upload_metadata
(
    id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    bank_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_size bigint,
    file_format character varying(50) COLLATE pg_catalog."default",
    upload_id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    blob_path character varying(500) COLLATE pg_catalog."default",
    blob_url character varying(500) COLLATE pg_catalog."default",
    row_count integer,
    column_count integer,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'uploaded'::character varying,
    schema_version character varying(50) COLLATE pg_catalog."default",
    upload_timestamp timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by character varying(36) COLLATE pg_catalog."default",
    updated_by character varying(36) COLLATE pg_catalog."default",
    version integer DEFAULT 1,
    deleted_at timestamp without time zone,
    is_deleted character varying(10) COLLATE pg_catalog."default" DEFAULT 'false'::character varying,
    file_metadata jsonb,
    schema_registry_id character varying(36) COLLATE pg_catalog."default",
    bronze_blob_path character varying(500) COLLATE pg_catalog."default",
    bronze_row_count integer,
    bronze_file_size_bytes bigint,
    bronze_checksum_sha256 character varying(64) COLLATE pg_catalog."default",
    bronze_status character varying(50) COLLATE pg_catalog."default",
    bronze_verified_at timestamp with time zone,
    CONSTRAINT upload_metadata_pkey PRIMARY KEY (id),
    CONSTRAINT upload_metadata_upload_id_key UNIQUE (upload_id)
);

ALTER TABLE IF EXISTS public.upload_metadata
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.webhook_configs
(
    organization_id uuid NOT NULL,
    url character varying(500) COLLATE pg_catalog."default" NOT NULL,
    events jsonb NOT NULL,
    is_active boolean NOT NULL,
    description character varying(200) COLLATE pg_catalog."default",
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT webhook_configs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.webhook_deliveries
(
    webhook_config_id uuid NOT NULL,
    event_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    payload jsonb NOT NULL,
    status webhook_delivery_status NOT NULL,
    attempt_count integer NOT NULL,
    last_attempt_at timestamp with time zone,
    response_status_code integer,
    response_body text COLLATE pg_catalog."default",
    error_message text COLLATE pg_catalog."default",
    delivered_at timestamp with time zone,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT webhook_deliveries_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.admin_user_roles
    ADD CONSTRAINT admin_user_roles_admin_user_id_fkey FOREIGN KEY (admin_user_id)
    REFERENCES public.admin_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.admin_user_roles
    ADD CONSTRAINT admin_user_roles_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.api_keys
    ADD CONSTRAINT api_keys_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.org_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.api_keys
    ADD CONSTRAINT api_keys_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_api_keys_organization_id
    ON public.api_keys(organization_id);


ALTER TABLE IF EXISTS public.api_keys
    ADD CONSTRAINT api_keys_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_api_keys_role_id
    ON public.api_keys(role_id);


ALTER TABLE IF EXISTS public.api_logs
    ADD CONSTRAINT api_logs_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_api_logs_organization_id
    ON public.api_logs(organization_id);


ALTER TABLE IF EXISTS public.batch_job_items
    ADD CONSTRAINT batch_job_items_batch_job_id_fkey FOREIGN KEY (batch_job_id)
    REFERENCES public.bulk_scoring_jobs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_batch_job_items_batch_job_id
    ON public.batch_job_items(batch_job_id);


ALTER TABLE IF EXISTS public.batch_job_items
    ADD CONSTRAINT batch_job_items_score_request_id_fkey FOREIGN KEY (score_request_id)
    REFERENCES public.score_requests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_batch_job_items_score_request_id
    ON public.batch_job_items(score_request_id);


ALTER TABLE IF EXISTS public.bronze_ingestion_log
    ADD CONSTRAINT bronze_ingestion_log_training_upload_id_fkey FOREIGN KEY (training_upload_id)
    REFERENCES public.training_uploads (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_bronze_log_training_upload_id
    ON public.bronze_ingestion_log(training_upload_id);


ALTER TABLE IF EXISTS public.bulk_scoring_jobs
    ADD CONSTRAINT bulk_scoring_jobs_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.org_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bulk_scoring_jobs
    ADD CONSTRAINT bulk_scoring_jobs_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_bulk_scoring_jobs_organization_id
    ON public.bulk_scoring_jobs(organization_id);


ALTER TABLE IF EXISTS public.decision_metrics
    ADD CONSTRAINT decision_metrics_scoring_result_id_fkey FOREIGN KEY (scoring_result_id)
    REFERENCES public.scoring_results (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_decision_metrics_scoring_result_id
    ON public.decision_metrics(scoring_result_id);


ALTER TABLE IF EXISTS public.field_mappings
    ADD CONSTRAINT field_mappings_training_upload_id_fkey FOREIGN KEY (training_upload_id)
    REFERENCES public.training_uploads (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_field_mappings_training_upload_id
    ON public.field_mappings(training_upload_id);


ALTER TABLE IF EXISTS public.loan_performances
    ADD CONSTRAINT loan_performances_score_request_id_fkey FOREIGN KEY (score_request_id)
    REFERENCES public.score_requests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_loan_performances_score_request_id
    ON public.loan_performances(score_request_id);


ALTER TABLE IF EXISTS public.mapping_templates
    ADD CONSTRAINT fk_mapping_templates_created_from_upload_id FOREIGN KEY (created_from_upload_id)
    REFERENCES public.training_uploads (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mapping_templates
    ADD CONSTRAINT mapping_templates_data_source_id_fkey FOREIGN KEY (data_source_id)
    REFERENCES public.data_sources (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_mapping_templates_data_source_id
    ON public.mapping_templates(data_source_id);


ALTER TABLE IF EXISTS public.message_deduplication
    ADD CONSTRAINT message_deduplication_run_id_fkey FOREIGN KEY (run_id)
    REFERENCES public.pipeline_runs (run_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.model_versions
    ADD CONSTRAINT model_versions_promoted_by_id_fkey FOREIGN KEY (promoted_by_id)
    REFERENCES public.admin_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.model_versions
    ADD CONSTRAINT model_versions_training_upload_id_fkey FOREIGN KEY (training_upload_id)
    REFERENCES public.training_uploads (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_model_versions_training_upload_id
    ON public.model_versions(training_upload_id);


ALTER TABLE IF EXISTS public.org_user_roles
    ADD CONSTRAINT org_user_roles_org_user_id_fkey FOREIGN KEY (org_user_id)
    REFERENCES public.org_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.org_user_roles
    ADD CONSTRAINT org_user_roles_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.org_users
    ADD CONSTRAINT org_users_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_org_users_organization_id
    ON public.org_users(organization_id);


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.roles
    ADD CONSTRAINT roles_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_roles_organization_id
    ON public.roles(organization_id);


ALTER TABLE IF EXISTS public.score_decisions
    ADD CONSTRAINT score_decisions_decided_by_user_id_fkey FOREIGN KEY (decided_by_user_id)
    REFERENCES public.org_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.score_decisions
    ADD CONSTRAINT score_decisions_score_request_id_fkey FOREIGN KEY (score_request_id)
    REFERENCES public.score_requests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS score_decisions_score_request_id_key
    ON public.score_decisions(score_request_id);


ALTER TABLE IF EXISTS public.score_requests
    ADD CONSTRAINT score_requests_api_key_id_fkey FOREIGN KEY (api_key_id)
    REFERENCES public.api_keys (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.score_requests
    ADD CONSTRAINT score_requests_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.org_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.score_requests
    ADD CONSTRAINT score_requests_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_score_requests_organization_id
    ON public.score_requests(organization_id);


ALTER TABLE IF EXISTS public.scoring_results
    ADD CONSTRAINT scoring_results_bulk_job_id_fkey FOREIGN KEY (bulk_job_id)
    REFERENCES public.bulk_scoring_jobs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_scoring_results_bulk_job_id
    ON public.scoring_results(bulk_job_id);


ALTER TABLE IF EXISTS public.scoring_results
    ADD CONSTRAINT scoring_results_score_request_id_fkey FOREIGN KEY (score_request_id)
    REFERENCES public.score_requests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_scoring_results_score_request_id
    ON public.scoring_results(score_request_id);


ALTER TABLE IF EXISTS public.system_completions
    ADD CONSTRAINT system_completions_run_id_fkey FOREIGN KEY (run_id)
    REFERENCES public.pipeline_runs (run_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.training_data_sources
    ADD CONSTRAINT training_data_sources_uploaded_by_id_fkey FOREIGN KEY (uploaded_by_id)
    REFERENCES public.admin_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training_uploads
    ADD CONSTRAINT training_uploads_approved_by_id_fkey FOREIGN KEY (approved_by_id)
    REFERENCES public.admin_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training_uploads
    ADD CONSTRAINT training_uploads_data_source_id_fkey FOREIGN KEY (data_source_id)
    REFERENCES public.data_sources (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_training_uploads_data_source_id
    ON public.training_uploads(data_source_id);


ALTER TABLE IF EXISTS public.training_uploads
    ADD CONSTRAINT training_uploads_mapping_template_id_fkey FOREIGN KEY (mapping_template_id)
    REFERENCES public.mapping_templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training_uploads
    ADD CONSTRAINT training_uploads_uploaded_by_id_fkey FOREIGN KEY (uploaded_by_id)
    REFERENCES public.admin_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.webhook_configs
    ADD CONSTRAINT webhook_configs_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_webhook_configs_organization_id
    ON public.webhook_configs(organization_id);


ALTER TABLE IF EXISTS public.webhook_deliveries
    ADD CONSTRAINT webhook_deliveries_webhook_config_id_fkey FOREIGN KEY (webhook_config_id)
    REFERENCES public.webhook_configs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_webhook_deliveries_webhook_config_id
    ON public.webhook_deliveries(webhook_config_id);

END;